### ISSUE TITLE
Luarocks Issues Thread

### ISSUE THREAD

**Issue by vhyrro** [nvim-neorg/neorg#1342]
If you're probably here you're either angry or you're sad :)

The latest update, `8.0.0`, has been a breaking change for users. This isn't a breaking change just because I felt like it, rather it paves the way forward for making Neorg expansive and more stable than it was before. We just need to jump through the initial hurdles.

If you have issues, please read the [blog post I made](https://vhyrro.github.io/posts/neorg-and-luarocks/#the-fix). It will have you covered on how to fix things.

If you don't want to deal with the breakages, feel free to roll back to version `v7.0.0` - everything will continue to run there.

If you're having errors in lazy, I highly encourage you to restart Neovim and try manually rerunning `:Lazy build luarocks.nvim` and, if that succeeds, running `:Lazy build neorg` afterwards. If you get any errors which you do not understand, please post them here!

Thank you lot for the patience! Happy note taking.

**Comment by roland-5** [comment]
I use lazy and `:Lazy build luarocks.nvim` and `:Lazy build neorg` indeed helped for error with error that I had.
Should we install `luarock` package from our distribution repository too?

**Comment by vhyrro** [comment]
Nope, you don't need the `luarocks` package from your distro :)

Yeah, sometimes manually rerunning the build steps is what fixes it. Lazy is very unpredictable when it comes to build steps :man_shrugging:

**Comment by pysan3** [comment]
For those who are on Arch Linux and seeing a build error similar to...

```txt
❌ Performing luarocks `./configure` if Unix systems
...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/build.lua:126: Failed to install luarocks: 
Configuring LuaRocks version dev...

Lua interpreter found: /sbin/luajit
Checking if /sbin/luajit is Lua version 5.1... yes
lua.h for Lua 5.1 not found (tried //include/lua/5.1/lua.h //include/lua5.1/lua.h //include/lua-5.1/lua.h //include/lua51/lua.h //include/lua.h //include/luajit-2.1/lua.h)

If the development files for Lua (headers and libraries)
are installed in your system, you may need to use the
--with-lua or --with-lua-include flags to specify their location.

If those files are not yet installed, you need to install
them using the appropriate method for your operating system.

Run ./configure --help for details on flags.

configure failed.
```

change your luarocks.nvim config as follows.

```lua
{
  "vhyrro/luarocks.nvim",
  opts = {
    luarocks_build_args = {
      "--with-lua-include=/usr/include",
    },
  },
}
```

**Comment by simonhughxyz** [comment]
I'm trying to install it with the lazy method but I keep getting an error:
``` vim
Failed to run `config` for neorg
                                                                                                                                         
.../lazy/neorg/lua/neorg/modules/core/highlights/module.lua:433: module 'nvim-treesitter.query' not found:No LuaRocks module found for nv
im-treesitter.query                                                                                                                      
^Ino field package.preload['nvim-treesitter.query']                                                                                      
cache_loader: module nvim-treesitter.query not found                                                                                     
cache_loader_lib: module nvim-treesitter.query not found                                                                                 
^Ino file './nvim-treesitter/query.lua'                                                                                                  
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/nvim-treesitter/query.lua'                                         
^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/query.lua'                                                                           
^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/query/init.lua'                                                                      
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/query.lua'                                            
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/nvim-treesitter/query/init.lua'                                       
^Ino file '/home/simon/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/nvim-treesitter/query.lua'                              
^Ino file '/home/simon/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/nvim-treesitter/query/init.lua'                         
^Ino file '/home/simon/.luarocks/share/lua/5.1/nvim-treesitter/query.lua'                                                                
^Ino file '/home/simon/.luarocks/share/lua/5.1/nvim-treesitter/query/init.lua'                                                           
^Ino file './nvim-treesitter/query.so'                                                                                                   
^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter/query.so'                                                                              
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter/query.so'                                               
^Ino file '/usr/local/lib/lua/5.1/loadall.so'                                                                                            
^Ino file '/home/simon/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/nvim-treesitter/query.so'                                 
^Ino file '/home/simon/.luarocks/lib/lua/5.1/nvim-treesitter/query.so'                                                                   
^Ino file './nvim-treesitter.so'                                                                                                         
^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter.so'                                                                                    
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/nvim-treesitter.so'                                                     
^Ino file '/usr/local/lib/lua/5.1/loadall.so'                                                                                            
^Ino file '/home/simon/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/nvim-treesitter.so'                                       
^Ino file '/home/simon/.luarocks/lib/lua/5.1/nvim-treesitter.so'                                                                         
                                                                                                                                         
# stacktrace:                                                                                                                            
  - /neorg/lua/neorg/modules/core/highlights/module.lua:433 _in_ **trigger_highlights**                                                  
  - /neorg/lua/neorg/modules/core/highlights/module.lua:420 _in_ **load**                                                                
  - /neorg/lua/neorg/core/modules.lua:403 _in_ **load_module**                                                                           
  - /neorg/lua/neorg/core/modules.lua:335 _in_ **load_module**  
```

**Comment by vhyrro** [comment]
@simonhughxyz The error message is slightly different as we're using the luarocks package loader, but the underlying cause looks to be the same - Neorg is trying to initialize before treesitter is activated.

Maybe try:
```lua
{
  "nvim-neorg/neorg",
  dependencies = { "luarocks.nvim", "nvim-treesitter" }, -- Add nvim-treesitter here
}
```

Just for good measure? I'll be revamping that part of the code fairly soon anyway, but it's worth a shot.

**Comment by simonhughxyz** [comment]
> ```lua
> "nvim-treesitter"
> ```

This fix did not work

**Comment by vhyrro** [comment]
Okay, I tried another thing. @simonhughxyz mind updating the plugin and trying again? I removed the old and hacky code related to nvim-treesitter query invalidation, which has been resolved for a while now.

**Comment by simonhughxyz** [comment]
No sorry, updated all plugin, still did not work. Tried deleting my nvim data folder as well just in case, did not resolve anything.

**Comment by vhyrro** [comment]
That's odd... are you pinned to the latest stable release by any chance? I pushed the update to the main branch.

I quite literally removed the old code that cause the error, so it continuing to trigger is quite suspicious :sweat_smile:

**Comment by simonhughxyz** [comment]
Yea, just checked lazy, it says its on commit `388976f`. So not latest. Not sure why, I updated neorg and like I said before even tried deleting my data folder.

**Comment by simonhughxyz** [comment]
Oh hang on, my bad, I had `version = "*"` in my lazy setup

**Comment by simonhughxyz** [comment]
Ok, so the latest commit got rid of the error, but neorg still will not load

**Comment by vhyrro** [comment]
I assume then that it's silently failing to load? All of the people that have mentioned such an error have had their issues resolved via `:Lazy build neorg`, which forces a rebuild of the project. After restarting Neovim things should start working once more :)

As I mentioned before, lazy has a notoriously weird set of build procedures.

**Comment by simonhughxyz** [comment]
Ok so I fixed it, it just needs 2 dependancies ` dependencies = { "luarocks.nvim", "nvim-treesitter/nvim-treesitter" },`
Everything works now.

**Comment by roland-5** [comment]
@vhyrro I use Arch and @pysan3 method worked for me. I installed `luarock` from Arch repository, deleted `~/.local/share/nvim` to test this, and with his change, everything were downloaded and built without problem this time.

**Comment by pysan3** [comment]
@roland-5 The workaround will be officially supported so you don't need to add the line in your config anymore. (Obviously adding `luarocks_build_args` it will finish faster cuz the workaround will retry a couple of times.)

- https://github.com/vhyrro/luarocks.nvim/pull/14

**Comment by zvpyp** [comment]
I might just add, if you are using fedora, make sure you have installed compat-lua-devel-5.1.5

`sudo dnf install compat-lua-devel-5.1.5`

The with-lua flag is not necessary since it is installed in a default directory.

Then you do `:Lazy build luarocks.nvim` and after that `:Lazy build luarocks.nvim`

Hope that helps, I was just frustrated searching for the package.

**Comment by ALVAROPING1** [comment]
> For those who are on Arch Linux and seeing a build error similar to...
> 
> ```
> ❌ Performing luarocks `./configure` if Unix systems
> ...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/build.lua:126: Failed to install luarocks: 
> Configuring LuaRocks version dev...
> 
> Lua interpreter found: /sbin/luajit
> Checking if /sbin/luajit is Lua version 5.1... yes
> lua.h for Lua 5.1 not found (tried //include/lua/5.1/lua.h //include/lua5.1/lua.h //include/lua-5.1/lua.h //include/lua51/lua.h //include/lua.h //include/luajit-2.1/lua.h)
> 
> If the development files for Lua (headers and libraries)
> are installed in your system, you may need to use the
> --with-lua or --with-lua-include flags to specify their location.
> 
> If those files are not yet installed, you need to install
> them using the appropriate method for your operating system.
> 
> Run ./configure --help for details on flags.
> 
> configure failed.
> ```
> 
> change your luarocks.nvim config as follows.
> 
> ```lua
> {
>   "vhyrro/luarocks.nvim",
>   opts = {
>     luarocks_build_args = {
>       "--with-lua-include=/usr/include",
>     },
>   },
> }
> ```

if you get an issue similar to this on ubuntu based distros, you need to install the `liblua5.1-0-dev` package

**Comment by dearieme** [comment]
Hello, noob question: how do I see the build errors in Lazy?

I'm getting the "Performing luarocks `./configure` if Unix systems" message when I run "Lazy build luarocks.nvim" but I can't figure out how to see the full errors. They do not seem to be in ":mess" or "NoiceHistory"

Thanks

**Comment by pysan3** [comment]
`:Notifications`

**Comment by dearieme** [comment]
@pysan3 Thank you, I'm sure I knew that once :)

I'm on Arch and the error suggested that lua 5.1 was explicitly required, so I installed"extra/lua51" ("extra/lua" was already installed but didn't conflict) re-did the Lazy build dance, and it all seems to work fine now.

**Comment by max397574** [comment]
I had strange errors with wget when trying to `Lazy build neorg`. I found out that just `wget` was broken (tested with `wget --version` which gave an error)
Just uninstalling `wget` made all the things work

**Comment by leongjs98** [comment]
@vhyrro 

I was unable to install Neorg v8 with lazy.nvim with [the blog post fix](https://vhyrro.github.io/posts/neorg-and-luarocks/#the-fix) here:

in the readme, it says:
> Using luarocks Neorg will install itself and these dependencies with their respective versions:

But for me, it didn't install the dependencies

I had to explicitly add these as dependencies to install Neorg v8:

```diff
  {
    "vhyrro/luarocks.nvim",
+   dependencies = {
+     "MunifTanjim/nui.nvim",
+     "nvim-neotest/nvim-nio",
+     "nvim-neorg/lua-utils.nvim",
+     "nvim-lua/plenary.nvim"
+   },
    priority = 1000, -- We'd like this plugin to load first out of the rest
    config = true,   -- This automatically runs `require("luarocks-nvim").setup()`
  },
```

Could you please update your blog post to add these in case someone had the same problem as me?

**Comment by skbolton** [comment]
I think the nixpkgs overlay flake is going to need an update. On a fresh system I was able to install without warnings but most of neorgs functionality is missing so I think it is in a bad state.

**Comment by flexagoon** [comment]
The configure script currently doesn't detect lua headers if lua is installed by Homebrew, because they're located in `/home/linuxbrew/.linuxbrew/Cellar/lua/5.4.6/include/lua/lua.h`

**Comment by flexagoon** [comment]
Also, for some reason, it tries to find the headers for lua 5.1, which has been deprecated

**Comment by pysan3** [comment]
@leongjs98 I don't think you have it setup correctly if you need those lines.

**Comment by pysan3** [comment]
@flexagoon You will need lua version 5.1 installed or luajit is better. 

I don't use brew so I'm not sure about the actual package name but if you install it, luarocks build script should be able to pick it up.

**Comment by flexagoon** [comment]
@pysan3 thanks, I installed luarocks from brew and luarocks.nvim built successfully.

However, Neorg still doesn't seem to work for some reason - the `:Neorg` command doesn't exist and I'm somehow not even getting Treesitter highlighting even though the norg TS parser is installed.

> FYI lua5.1 is not deprecated

I see, I assumed it was deprecated because Homebrew said that when I tried to install `lua@5.1`, turns out Homebrew just deprecates old versions of packages after a while

**Comment by pysan3** [comment]
> @vhyrro
> 
> I was unable to install Neorg v8 with lazy.nvim with [the blog post fix](https://vhyrro.github.io/posts/neorg-and-luarocks/#the-fix) here:
> 
> in the readme, it says:
> 
> > Using luarocks Neorg will install itself and these dependencies with their respective versions:
> 
> But for me, it didn't install the dependencies
> 
> I had to explicitly add these as dependencies to install Neorg v8:
> 
> ```diff
>   {
>     "vhyrro/luarocks.nvim",
> +   dependencies = {
> +     "MunifTanjim/nui.nvim",
> +     "nvim-neotest/nvim-nio",
> +     "nvim-neorg/lua-utils.nvim",
> +     "nvim-lua/plenary.nvim"
> +   },
>     priority = 1000, -- We'd like this plugin to load first out of the rest
>     config = true,   -- This automatically runs `require("luarocks-nvim").setup()`
>   },
> ```
> 
> Could you please update your blog post to add these in case someone had the same problem as me?

@leongjs98 What this implies is that you failed to install luarocks.nvim correctly.
The whole reason of using luarocks is to pin the dependency version [by the developers](https://github.com/nvim-neorg/neorg/blob/5ecf47bb566b5b94a99ea98650c7ad94d5e25321/build.lua#L14-L19) which with lazy.nvim and your setup it is not possible to do.

I wrote some instructions on how to debug your situation so please take a look. I hope this helps.

https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md

**Comment by smsossah** [comment]
All of the solutions I'm seeing here appear to be for lazy.nvim but I'm running into a bunch of errors using packer on a mac. I've tried troubleshooting some of these without success. This was working as expected prior to the Neorg updates. Is there any way you could post a more detailed guide for packer @vhyrro? Thanks!

**Comment by flexagoon** [comment]
@smsossah there is an updated installation code for packer in the readme, did you use that?

**Comment by pysan3** [comment]
@smsossah TBH packer.nvim is not fully tested.

I assume you use `pckr.nvim` and could you try to add
```lua
  "rcarriga/nvim-notify",
  {
    "vhyrro/luarocks.nvim",
    requires = { "rcarriga/nvim-notify" },
    run = [[:source ~/.local/share/pablomartan/site/pack/pckr/opt/luarocks.nvim/build.lua]],
    config = function()
      require("luarocks-nvim").setup({})
    en
  },
```

And restart neovim and see luarocks being installed.
You should also see some notifications that it's compiling luarocks.

After that, add neorg back again since `run = ` requires luarocks to be installed and pckr is not clever enough to resolve this dependency.

```lua
  {
    "nvim-neorg/neorg",
    requires = {
      "vhyrro/luarocks.nvim",
      "rcarriga/nvim-notify",
      "nvim-treesitter/nvim-treesitter",
    },
    run = [[:source ~/.local/share/pablomartan/site/pack/pckr/opt/neorg/build.lua]],
    config = function()
      require("neorg").setup()
    end,
  },
```

Again this is not officially tested.

**Comment by kavfkah** [comment]
> Any help for nixos? running `:Lazy build luarocks.nvim` tells me it can't find lua header files. I have no idea where they are located for nixos tho.

I'm using nixos as well and this ugly workaround to install luarocks from here as worked for me: https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md#performing-luarocks-configure-if-unix-systems

I'm stuck at installing neorg though, `:Lazy build neorg` says that rocks is installed and lazy says neorg installed, but I don't have the `:Neorg` command and there is no log or notification from neovim or lazy or neorg on what is wrong.

I really hope this luarocks stuff doesn't get any traction, just messes with so many things that would require different workarounds for every system I use (as is seen by this thread of problems).

**Comment by pysan3** [comment]
@kavfkah what is the result of `:=require("lua-util")`?

Also check neorg is not being lazy loaded or you have `cmd = "Neorg"` in lazy spec. 

If you still cannot make it to work, please come to discord and ping me (same username).

**Comment by kavfkah** [comment]
@pysan3 

`:=require("lua-util")`
```
20:46:10 msg_show.echo   Notifications 2024-03-27T20:45:37 Messages  INFO 2024-03-27T20:44:22 Error  ERROR E5108: Error executing lua [string ":lua"]:1: module 'lua-util' not found:No LuaRocks module found for lua-util
	no field package.preload['lua-util']
cache_loader: module lua-util not found
cache_loader_lib: module lua-util not found
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/lua-util.lua'
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/lua-util/init.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/lua-util.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/lua-util/init.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/lua-util.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/lua-util/init.lua'
	no file '/home/user/.luarocks/share/lua/5.1/lua-util.lua'
	no file '/home/user/.luarocks/share/lua/5.1/lua-util/init.lua'
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/lib/lua/5.1/lua-util.so'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/lua-util.so'
	no file '/home/user/.luarocks/lib/lua/5.1/lua-util.so'
stack traceback:
	[C]: in function 'require'
	[string ":lua"]:1: in main chunk

```

neorg.lua:
```
local M = {
    "nvim-neorg/neorg",
    dependencies = { "luarocks.nvim" },
    lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
    version = "*", -- Pin Neorg to the latest stable release
    config = true,
}

return M
```
luarocks.lua:
```
local M = {
    "vhyrro/luarocks.nvim",
    priority = 1000,
    opts = {
        luarocks_build_args = {
            "--with-lua-include=/nix/store/98blcb69q9qy0k279xjk10lcmfwnd4rg-luajit-2.1.1693350652/include"
        }
    }
}

return M

```
`:Lazy build luarocks.nvim` (no output)
`:Lazy build neorg`
```
20:54:20 msg_show.echo   Notifications  2024-03-27T20:54:15 Messages  INFO 2024-03-27T20:53:57 luarocks.nvim  INFO ⌛ Installing rocks:

nvim-nio ~> 1.7,lua-utils.nvim == 1.0.2,plenary.nvim == 0.1.4,nui.nvim == 0.3.0
2024-03-27T20:53:58 luarocks.nvim  INFO ✅ Installed rocks
```

**Comment by pysan3** [comment]
@kavfkah I'm sorry, it was `lua-utils` (plural).

Could you update your comment?

**Comment by kavfkah** [comment]
@pysan3 ups, updated, didn't check myself what it was supposed to install either, just copy-pasted

**Comment by pysan3** [comment]
Thanks @kavfkah 

Did you restart neovim after building neorg?

Besides that could you try the followings for neorg spec? (No need to change luarocks.nvim).

- Change to `version = false`, rerun `:Lazy sync` and maybe `:Lazy build neorg` 
- Change `config =` to
```lua
config = function()
  require("neorg").setup() -- NO arguments to setup()
end,
```

TBH I cannot spot anything wrong with your outputs. You do have luarocks.nvim setup correctly to say the least and this shouldn't be a problem with NixOS either...

**Comment by kavfkah** [comment]
> Did you restart neovim after building neorg?

Yes, I did that a few times


> ```lua
> config = function()
>   require("neorg").setup() -- NO arguments to setup()
> end,
> ```

this fixed it! `:Neorg` is available now. The version=false didn't matter though, it works both ways with the setup function called, and with none of both if I do config=true again

(btw I then also tried

```lua
    require("neorg").setup({
        load = {
            ["core.defaults"] = {},
            ["core.norg.concealer"] = {},
        }
    })
```
and did the Lazy build luarocks and Neorg again and got this error:
```
21:43:00 msg_show.echo   Notifications 2024-03-27T21:42:54  ERROR [neorg] (21:42:54)
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:447
Unable to load module 'core.norg.concealer'. The module probably does not exist! Stacktrace:  module 'neorg.modules.core.norg.concealer.module' not found:No LuaRocks module found for neorg.modules.core.norg.concealer.module
	no field package.preload['neorg.modules.core.norg.concealer.module']
cache_loader: module neorg.modules.core.norg.concealer.module not found
cache_loader_lib: module neorg.modules.core.norg.concealer.module not found
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/neorg/modules/core/norg/concealer/module.lua'
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/share/lua/5.1/neorg/modules/core/norg/concealer/module/init.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/norg/concealer/module.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/norg/concealer/module/init.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/norg/concealer/module.lua'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/norg/concealer/module/init.lua'
	no file '/home/user/.luarocks/share/lua/5.1/neorg/modules/core/norg/concealer/module.lua'
	no file '/home/user/.luarocks/share/lua/5.1/neorg/modules/core/norg/concealer/module/init.lua'
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/lib/lua/5.1/neorg/modules/core/norg/concealer/module.so'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg/modules/core/norg/concealer/module.so'
	no file '/home/user/.luarocks/lib/lua/5.1/neorg/modules/core/norg/concealer/module.so'
	no file '/nix/store/s5mxagjxsacpzvpvazh4cgsfnphkd6kj-luajit-2.1.1693350652-env/lib/lua/5.1/neorg.so'
	no file '/home/user/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg.so'
	no file '/home/user/.luarocks/lib/lua/5.1/neorg.so'
```
but I am not sure if it should simply work like that, I'll wait for the wiki updates if that is the case, as I just copied it from the now-outdated tutorial video)

**Comment by benlubas** [comment]
@kavfkah it's `core.concealer` now, not `core.norg.concealer`

**Comment by pysan3** [comment]
@morrismuehl @kavfkah 

All nix users, @benlubas merged a way better setup for nix users. Big thanks <3

Check it out! https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md#nixos

**Comment by kavfkah** [comment]
@benlubas ah thanks, it's working now, I see now that it's correct in the wiki, my bad

**Comment by CRAG666** [comment]
  Error  16:39:43 msg_show.lua_error   Lazy build neorg Error executing vim.schedule lua callback: ...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:27: [luarocks] Failed to install from rockspec
Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/think-crag/.cache/luarocks/https___luarocks.org/manifest-5.1.zip
Warning: Failed searching manifest: Failed loading manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/: /home/think-crag/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest-5.1: No such file or directory
Warning: Failed searching manifest: Failed loading manifest for https://luafr.org/luarocks/: /home/think-crag/.cache/luarocks/https___luafr.org_luarocks/manifest-5.1: No such file or directory
Warning: Failed searching manifest: Failed downloading http://luarocks.logiceditor.com/rocks/manifest-5.1 - failed downloading http://luarocks.logiceditor.com/rocks/manifest-5.1

Error: Could not satisfy dependency nvim-nio ~> 1.7: No results matching query were found for Lua 5.1.
Missing dependencies for neovim-rocks-user-rockspec 0.0-0:
   nvim-nio ~> 1.7 (not installed)
   lua-utils.nvim 1.0.2 (not installed)
   plenary.nvim 0.1.4 (not installed)
   nui.nvim 0.3.0 (not installed)

neovim-rocks-user-rockspec 0.0-0 depends on nvim-nio ~> 1.7 (not installed)

stack traceback:
	[C]: in function 'assert'
	...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:27: in function 'install'
	...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:60: in function 'ensure'
	/home/think-crag/.local/share/nvim/lazy/neorg/build.lua:14: in function </home/think-crag/.local/share/nvim/lazy/neorg/build.lua:9>

**Comment by flexagoon** [comment]
@CRAG666 what does `:Lazy build luarocks.nvim` output?

Also, please format error messages as code blocks, they're very hard to read otherwise

**Comment by morrismuehl** [comment]
@pysan3 First of all, thank you!

I know it's a bit much to ask. But is there a way to go about this in home manager? I have compiled neovim-nightly with magick installed for image.nvim, and I think the 2 options clash somewhat. Or at least I haven't gotten it to work so far.

**Comment by benlubas** [comment]
@morrismuehl I have both of them working, I'm also compiling nightly with the magick rock installed via nix. I don't think they conflict. 

Alternatively, you could install all of neorg's luarock deps the same way you're installing the magick rock and then disable the neorg's build script, though you'll have to manually update the deps when neorg updates.

**Comment by pysan3** [comment]
@morrismuehl unfortunately I have no plans to support Nix users in my tutorial (unless someone makes a PR; I will blindly accept it without testing). 

There are many awesome nix users on [Discord](https://discord.gg/T6EgTAX7ht) so you might want to ask them.

**Comment by BoltsJ** [comment]
I can't get this to work. I'll miss this plugin, but luarocks is proving to be too much of a headache. I'm not not "all in" on lua and am not going to layer packages into my ostree system just for a notes plugin.

**Comment by flexagoon** [comment]
@BoltsJ the only package this requires is luajit. You can layer it, or install it in a Toolbox, or from Homebrew, or whatever package installation method you prefer.

This isn't the only nvim plugin with external dependencies - there are, for example, many LSP servers that require node.js to be installed, and TreeSitter parsers require gcc, which is also not pre-installed on Silverblue. Not sure why you're so opposed to luajit specifically.

**Comment by BoltsJ** [comment]
I don't edit my notes from toolbox. I don't want to set up a toolbox just for note-taking.

**Comment by faldor20** [comment]
I had the same issue as @CRAG666 where i got a bunch of weird manifest errors and this:
`Error: Could not satisfy dependency nvim-nio ~> 1.7: No results matching query were found for Lua 5.1.`
Turns out i had the busybox version of `wget` installed I tested this by running `wget --version` which said "busybox"
@pysan3 Maybe you could specify that as a debug step in your migration guide :)

**Comment by pysan3** [comment]
@faldor20 PR welcome ;)

**Comment by austinbutler** [comment]
For Nix could this not be included in https://github.com/nvim-neorg/nixpkgs-neorg-overlay?

**Comment by moebiusband73** [comment]
Can you elaborate why you are doing this? Also why you need to build luarocks and not use the one that is provided on the system already. The dependency on lua 5.1 (a release that is more than 13 years old) and which I cannot install with homebrew anymore is a deal breaker for me. I am not into lua, but I hope they do not do the same mistake Python did with this Python 2 vs 3 mess.

Bottomline: I don't care. Neorg should be a tool I use and not something I waste my time with. I cannot believe that installing a custom package manager with a very new and obviously immature neovim plugin is really required to push forward this project. At the moment you make it hard to impossible for others to use this plugin. This looked promising, but I cannot rely on something for daily work that breaks all the time.

**Comment by benlubas** [comment]
@moebiusband73 pin to `v7.*` then. Your plugin will not break, and you can update whenever you have the time. Also, as far as I know, there is no issue installing on macos via brew. In fact, it's the recommended way to install in the [tutorial's migration guide](https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md)).

As far as why the project is moving in this direction, the reasoning is pretty clear in the blog post linked at the top of the thread.

**Comment by flexagoon** [comment]
> The dependency on lua 5.1 (a release that is more than 13 years old) and which I cannot install with homebrew anymore is a deal breaker for me

@moebiusband73 you can install `luajit` with Homebrew, it works as well.

**Comment by moebiusband73** [comment]
Well luajiit got me a few steps further, Neorg is still missing plugins. The thing is that developers accept to provide a fragile product. And yes I am aware this is OpenSource and I do not pay for it. I also develop Open Source tools, but I still feel a responsibility to not make things for my users more difficult.  I switched from vim to nvim 2 years ago and while I like the features of nvim, the overall experience is a lot more fragile. All the time stuff breaks, plugins fail to install or build (I also happen to have an OpenBSD Laptop) and certain functionality is not available anymore. The text editor is my most important tool and I just cannot afford to fix things before being able to work.

Now back to this issue, setting up a complete duplicate package manager within nvim sounds like a really terrible idea to me.  Especially because it does not seem to integrate well with Lazy, which is one of the more popular package manager out there. You argue this makes things easier, but at the moment this is a one man show and the believe that all the different setups, OS and environments just work like that are overoptimistic to say the least. Good luck, you seem to have very good nerves and hopefully a lot of time!

And yes everything can be fixed, but I just don't have the time to debug and fix a tool that I urgently need and that should be the most reliable thing on my computer.

**Comment by morrismuehl** [comment]
@benlubas 

I changed my nix config to not use hm, essentially to the snippet that you provided in the manual. Neorg works now (albeit somewhat unreliably), but I am no longer running the nightly version of neovim. If I understood correctly you are running nightly so I don't really understand why. Any idea what the problem is, or where I could look for help?

**Comment by vhyrro** [comment]
@moebiusband73  everything continues to just work if you pin to version 7 and wait for us to resolve the issues :)

> The thing is that developers accept to provide a fragile product

This is untrue for many reasons. The most obvious being that we version everything. If the setup is not running on your end, that's lazy deciding not to run the build script, not us. Hence it's not Neorg being fragile. Luarocks isn't something new at all, it has been around for a long while (even during the packer days).

Furthermore, it's far from a one-man show. There are now several dozens of plugins (including basically all of the most popular ones) on luarocks. If my memory serves me right four new ones landed in the mainline repository just yesterday. Those plugins can afford to keep backwards-compatibility, and that's awesome. If Neorg could provide perfect compatibility, it would, but as you can see from the blog posts, it simply can't :p

I understand that things "just working" and ease of use/debugging is of high priority, and that's exactly what I'm working towards with all of this. I'll also be looking at lazy to see if I can make the build logic more consistent (perhaps folke will be kind enough to look into himself, he's the wizard after all). I'm exclusively dedicating developer time to make the whole experience not just on par with what we had before, but better than what we had before. I'll be conjuring up kickstart configurations which get you started with an immediate working version of Neorg as well as guides.

Neorg is not your average "minimal, markdown based note taking tool" Neovim plugin. Testing the limits of what's possible is a part of what we do. Hope that clears things up, feel free to ask about anything if you need further answers :)

**Comment by vhyrro** [comment]
As for everyone else who might be having Neorg problems, sorry, I've been away for the past four days. I'll be looking into all of your issues and making some parts easier to debug. I just made the checkhealth more advanced which is a good start :)

**Comment by benlubas** [comment]
> @benlubas
> 
> I changed my nix config to not use hm, essentially to the snippet that you provided in the manual. Neorg works now (albeit somewhat unreliably), but I am no longer running the nightly version of neovim. If I understood correctly you are running nightly so I don't really understand why. Any idea what the problem is, or where I could look for help?

Yup I'm running nightly, the snippet in the tutorial is slightly simplified from my actual setup. I build nightly from source, I specify the source as an input to my system flake and then pass it as the source to `wrapNeovimUnstable`. I pin the version of nightly that I'm using b/c the latest version at the time I switched to nightly was crashing so I had to pin. That crash might be resolved if you want to try to build the latest nightly, but I'm not sure.

[defining the input](https://github.com/benlubas/nix-config/blob/35ad9cb1afc555b4319999be843f81a08beeebe0/flake.nix#L25)
[using that input](https://github.com/benlubas/nix-config/blob/35ad9cb1afc555b4319999be843f81a08beeebe0/programs/neovim.nix#L44)

---

What do you mean by "somewhat unreliably"?

**Comment by moebiusband73** [comment]
> @moebiusband73 everything continues to just work if you pin to version 7 and wait for us to resolve the issues :)
> 
> > The thing is that developers accept to provide a fragile product
> 
> This is untrue for many reasons. The most obvious being that we version everything. If the setup is not running on your end, that's lazy deciding not to run the build script, not us. Hence it's not Neorg being fragile. Luarocks isn't something new at all, it has been around for a long while (even during the packer days).
> 
> Furthermore, it's far from a one-man show. There are now several dozens of plugins (including basically all of the most popular ones) on luarocks. If my memory serves me right four new ones landed in the mainline repository just yesterday. Those plugins can afford to keep backwards-compatibility, and that's awesome. If Neorg could provide perfect compatibility, it would, but as you can see from the blog posts, it simply can't :p
> 
> I understand that things "just working" and ease of use/debugging is of high priority, and that's exactly what I'm working towards with all of this. I'll also be looking at lazy to see if I can make the build logic more consistent (perhaps folke will be kind enough to look into himself, he's the wizard after all). I'm exclusively dedicating developer time to make the whole experience not just on par with what we had before, but better than what we had before. I'll be conjuring up kickstart configurations which get you started with an immediate working version of Neorg as well as guides.
> 
> Neorg is not your average "minimal, markdown based note taking tool" Neovim plugin. Testing the limits of what's possible is a part of what we do. Hope that clears things up, feel free to ask about anything if you need further answers :)

I understood Neorg should be the generic format  to support basically any notetaking situation. But why then put it into one probably more and more complex plugin and not split it up. Have a basic plugin with just the essential functionality, and then add other plugins with the more fancy stuff. This would not make users hostage of adding new features they are not interested in.

I am not sure if I am the only one, but I just need a simple note taking format with a robust syntax, good syntax highlighting, linking between notes, good native Telescope integration, and nice conceal support. Thats it, all the other fancy things: Don't need it. So testing the limits of whats possible is not one of my requirements :-). Btw before I used Telekasten which can do most of that. Maybe one can support neorg files there.

So thanks for clarifying, I guess Neorg is just not for me. A pity, I liked the syntax. Maybe I fork it ;-), or is there already a fork with less ambitious aims?

**Comment by pysan3** [comment]
@moebiusband73 

- https://vhyrro.github.io/posts/neorg-and-luarocks/
- https://github.com/nvim-neorg/neorg/issues/1342
- https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md

If you still can't make it to work, paste your error message here. 
Let's move towards solving the problem and not take your time to write long comments.

**Comment by morrismuehl** [comment]
@benlubas 

Thanks again, I am not using flakes yet but I might look into it if I find the time.

"Unreliably" meant, sometimes it works, sometimes it doesn't. I can execute commands but markup doesn't work and neither does following links.
I can restart nvim and things will probably be fine. Neorg seems to be loaded even if it doesn't work (I can execute neorg commands in console).  

But I am not sure whether that has anything to do with Neorg. VimTeX stopped working on me today and all sorts of plugins started misbehaving ever since adopting that config (even just highlighting in *.nix files started becoming super janky). I'll revert to my old config with Neorg 7.0 for now.

**Comment by LonelyMusicDisc** [comment]
Has anyone gotten luarocks and by extension Neorg working on Windows? I tried to help my friend install it there, but in the end `lua-utils is not found` got the best of me and I told him to use 7.0.0 instead.

**Comment by vhyrro** [comment]
@LonelyMusicDisc we've had a decent chunk of windows testers and it should work as expected there. Did your friend have lua installed on their system with something like LuaForWindows as stated in the luarocks.nvim readme?

As always make sure to `:Lazy build luarocks.nvim` and `:Lazy build neorg`. I'll try my best to improve the build.lua detection within lazy soon!

**Comment by LonelyMusicDisc** [comment]
So I fixed his install and learned that installing lua-for-windows on scoop does not work the same as installing lua-for-windows normally, do not use scoop!

**Comment by tmccombs** [comment]
Is there a way I can use my existing installation of luarocks on my system (archlinux) with lazy.nvim?

Or installing directly with luarocks? 

I really don't love the idea of using another plugin that builds a new installation of luarocks when I already have luarocks installed.  

And I don't really want to switch to a new package manager either, espeically since rocks.nvim is missiong functionality that lazy.nvim has (such as configuring a plugin to lazily load on certain key mappings or commands, semantic versioning for git repo tags, etc.)

**Comment by austinbutler** [comment]
What's working for me currently on Nix with `home-manager` is adding to [`extraLuaPackages`](https://nix-community.github.io/home-manager/options.xhtml#opt-programs.neovim.extraLuaPackages).

```nix
  extraLuaPackages = luaPkgs: with luaPkgs; [lua-utils-nvim nvim-nio pathlib-nvim];
```

Telescope is still half-broken, but I assume that's https://github.com/nvim-neorg/neorg-telescope/issues/57.

**Comment by maxdiebold** [comment]
@morrismuehl I was able to get rocks working with home-manager by adding `luajit` (which is for Lua 5.1) to `extraPackages`, where I had been using the `lua` package. The `lua` package is set to a more recent version by default, but overriding the version would probably work, too, e.g. `pkgs.lua.override { version = "5.1" };`.

Why do the instructions advise setting `lazy` to false? I have no issues lazy loading, and I'd rather keep it that way, since I obviously won't be using Neorg for non-`norg` files.

**Comment by maxdiebold** [comment]
@pysan3 I've found that I can still get the completions on the first try by setting `cmd = "Neorg"` in Lazy's plugin spec, but I will keep the second point in mind if I run into any issues!

**Comment by mikolajpp** [comment]
> @vhyrro
> 
> I was unable to install Neorg v8 with lazy.nvim with [the blog post fix](https://vhyrro.github.io/posts/neorg-and-luarocks/#the-fix) here:
> 
> in the readme, it says:
> 
> > Using luarocks Neorg will install itself and these dependencies with their respective versions:
> 
> But for me, it didn't install the dependencies
> 
> I had to explicitly add these as dependencies to install Neorg v8:
> 
> ```diff
>   {
>     "vhyrro/luarocks.nvim",
> +   dependencies = {
> +     "MunifTanjim/nui.nvim",
> +     "nvim-neotest/nvim-nio",
> +     "nvim-neorg/lua-utils.nvim",
> +     "nvim-lua/plenary.nvim"
> +   },
>     priority = 1000, -- We'd like this plugin to load first out of the rest
>     config = true,   -- This automatically runs `require("luarocks-nvim").setup()`
>   },
> ```
> 
> Could you please update your blog post to add these in case someone had the same problem as me?

I needed this to install neorg with Lunar vim on OSX. It would miss lua-utils.

**Comment by mikolajpp** [comment]
Nothing in this thread or in any resource I found helped me to install on current Lunar Vim stable (Neovim 0.9.0).
All attempts failed with `lua-utils` not found error. Eventually, close to giving up, I decided to install Lunar Vim nightly (Neovim 0.10.0). Apparently there is a (better?) support for luarocks and the installation worked with the stock config!

**Comment by vhyrro** [comment]
@Anrock hey, yes Neorg still relies on treesitter. That was a huge oversight on my part when making the rocks.nvim install instructions, so sorry for that.

With #1390 this will no longer be the case. I hope to merge that later today, just trying to fix some things in the rocks-binaries repo!

**Comment by bdpierce777** [comment]
> Ok so I fixed it, it just needs 2 dependancies ` dependencies = { "luarocks.nvim", "nvim-treesitter/nvim-treesitter" },` Everything works now.

This did the trick for me using the "lazy kickstart"
The "pure luarocks" config seemed really cool...but I couldn't get it working

**Comment by arunoruto** [comment]
I currently use [nixvim](https://nix-community.github.io/nixvim/plugins/neorg/index.html) in home-manager to manage my neorg config under nixos, and I always get the following warning:
```log
Warning [neorg]: lua-utils not found. If you're just installing the plugin, ignore this message, when in doubt run `:Lazy build neorg`. If you're not on lazy please rerun the build scripts.
```

My neorg.nix file looks like this:
```nix
{pkgs, ...}: {
  programs.nixvim = {
    plugins = {
      neorg = {
        enable = true;
        modules = {
          "core.defaults".__empty = null;
          "core.concealer" = {
            config = {
              icon_preset = "basic";
            };
          };
          "core.dirman" = {
            config = {
              workspaces = {
                notes = "~/Documents/notes";
              };
              default_workspace = "notes";
            };
          };
        };
      };
    };
    extraLuaPackages = with pkgs.luaPackages; [
      lua-utils-nvim
      nvim-nio
      pathlib-nvim
    ];
  };
}
```
I followed @austinbutler [comment](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2052507275) to add the three packages to `extraLuaPackages` (which is also available in `nixvim`), but to no avail.

And whenever I am running `home-manager switch` I get the following warning about treesitter:
```log
warning: Neorg's `core.defaults` module is enabled but `plugins.treesitter` is not.
Treesitter is required when using the `core.defaults`.
```
Treesitter is for sure enabled and works fine, but something is messed up in nixvim.

**Comment by glyh** [comment]
I got 
```
Warning [neorg]: lua-utils not found. If you're just installing the plugin, ignore this message, when in doubt run `:Lazy 
build neorg`. If you're not on lazy please rerun the build scripts.   
```

No matter how I rerun `:Lazy build neorg`, what should I do?

**Comment by clemenscodes** [comment]
@arunoruto I also use `nixvim`, did not have any luck either using their plugin option. However, I managed to fix it using the official [neorg-overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) instead and adding the overridden plugin manually:
```nix
{
  pkgs,
  config,
  lib,
  ...
}: let
  cfg = config.nixvim.neorg;
in
  with lib; {
    options = {
      nixvim = {
        neorg = {
          enable = mkEnableOption "Enable neorg for nixvim" // {default = true;};
        };
      };
    };
    config = mkIf (config.nixvim.enable && cfg.enable) {
      programs = {
        nixvim = {
          extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
          extraConfigLuaPost =
            /*
            lua
            */
            ''
              require("neorg").setup {
                load = {
                  ["core.defaults"] = {}
                }
              }
            '';
        };
      };
    };
  }
 ```

**Comment by kjkent** [comment]
First time installing neorg here and I seem to be getting the same issue as a few people in this thread. I followed the instructions for Lazy.nvim and everything _appears_ to install correctly, but every time I start nvim, I get:
```
Warning [neorg]: lua-utils not found. If you're just installing the plugin, ignore this message, when in
doubt run `:Lazy build neorg`. If you're not on lazy please rerun the build scripts.
```
`:checkhealth neorg` reports:
```
neorg: require("neorg.health").check()

neorg
- Checking configuration...
- OK Empty configuration provided: Neorg will load core.defaults by default.
- Checking existence of dependencies...
- OK Required dependency vhyrro/luarocks found!
- Checking existence of luarocks dependencies...
- ERROR Critical dependency lua-utils.nvim not found! Please run :Lazy build luarocks.nvim and then      :Lazy build neorg! Neorg will refuse to load.
```
Unfortunately the suggested build commands do not help. I'm running Arch Linux.

**Comment by pysan3** [comment]
@kjkent Do you have system dependencies installed?

https://github.com/pysan3/Norg-Tutorial/blob/main/MIGRATION-v8.md#install-system-dependencies

**Comment by kjkent** [comment]
@pysan3 `luajit` and `lua51`? If so, yes, both installed.

**Comment by Mourey** [comment]
Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!

**Comment by clemenscodes** [comment]
> Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!

See here: https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2137724840

**Comment by Mourey** [comment]
> @arunoruto I also use `nixvim`, did not have any luck either using their plugin option. However, I managed to fix it using the official [neorg-overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) instead and adding the overridden plugin manually:
> 
> ```nix
> {
>   pkgs,
>   config,
>   lib,
>   ...
> }: let
>   cfg = config.nixvim.neorg;
> in
>   with lib; {
>     options = {
>       nixvim = {
>         neorg = {
>           enable = mkEnableOption "Enable neorg for nixvim" // {default = true;};
>         };
>       };
>     };
>     config = mkIf (config.nixvim.enable && cfg.enable) {
>       programs = {
>         nixvim = {
>           extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
>           extraConfigLuaPost =
>             /*
>             lua
>             */
>             ''
>               require("neorg").setup {
>                 load = {
>                   ["core.defaults"] = {}
>                 }
>               }
>             '';
>         };
>       };
>     };
>   }
> ```

I'm not sure I follow on this, When I add this file to my files I get a attribute 'enable' missing.

**Comment by Mourey** [comment]
> > Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!
> 
> See here: [#1342 (comment)](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2137724840)

I don't quite follow your solution, adding your configuration is not really working for me

`       error: attribute 'enable' missing

       at /nix/store/sdnwlvck6a2l6lvl7q9chsqv4m737wjn-source/homeManagerModules/neo.nix:17:20:

           16|     };
           17|     config = mkIf (config.nixvim.enable && cfg.enable) {
             |                    ^
           18|       programs = {
          
  `

**Comment by clemenscodes** [comment]
> > > Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!
> > 
> > 
> > See here: [#1342 (comment)](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2137724840)
> 
> I don't quite follow your solution, adding your configuration is not really working for me
> 
> ` error: attribute 'enable' missing
> 
> ```
>    at /nix/store/sdnwlvck6a2l6lvl7q9chsqv4m737wjn-source/homeManagerModules/neo.nix:17:20:
> 
>        16|     };
>        17|     config = mkIf (config.nixvim.enable && cfg.enable) {
>          |                    ^
>        18|       programs = {
> ```
> 
> `

This is a minimal module without custom options:
```nix
{pkgs, ...}: {
  programs = {
    nixvim = {
      enable = true;
      extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
      extraConfigLuaPost = ''
        require("neorg").setup {
          load = {
            ["core.defaults"] = {},
          },
        }
      '';
    };
  };
}
  ```
  
Note that this uses the mentioned [overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay). To use it, you have to first be using flakes, and then add it as a flake input in your `flake.nix` and add the overlay the overlays of your `nixpkgs`. The [link](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) gives an example on how to do that.

**Comment by Mourey** [comment]
> > > > Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!
> > > 
> > > 
> > > See here: [#1342 (comment)](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2137724840)
> > 
> > 
> > I don't quite follow your solution, adding your configuration is not really working for me
> > ` error: attribute 'enable' missing
> > ```
> >    at /nix/store/sdnwlvck6a2l6lvl7q9chsqv4m737wjn-source/homeManagerModules/neo.nix:17:20:
> > 
> >        16|     };
> >        17|     config = mkIf (config.nixvim.enable && cfg.enable) {
> >          |                    ^
> >        18|       programs = {
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `
> 
> This is a minimal module without custom options:
> 
> ```nix
> {pkgs, ...}: {
>   programs = {
>     nixvim = {
>       enable = true;
>       extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
>       extraConfigLuaPost = ''
>         require("neorg").setup {
>           load = {
>             ["core.defaults"] = {},
>           },
>         }
>       '';
>     };
>   };
> }
> ```
> 
> Note that this uses the mentioned [overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay). To use it, you have to first be using flakes, and then add it as a flake input in your `flake.nix` and add the overlay to the overlays of your `nixpkgs`. The [link](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) gives an example on how to do that.

Thank you for your support and help, you helped me learn something new. I was not aware that under a home-manager set up I had to import the overlay directly on my home.nix ( my file structure is something like: flake.nix that imports configuration.nix (os) and in turn configuration.nix imports home.nix (home-manager)).

In essence by adding the overlay to home-manager solved the issue and I now have Neorg in my through my Nixvim configuration using the overlay!

Thank you!

**Comment by clemenscodes** [comment]
> > > > > Hi If anyone has managed to get it to work on Nixvim, would appreciate comments on how the managed it!
> > > > 
> > > > 
> > > > See here: [#1342 (comment)](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2137724840)
> > > 
> > > 
> > > I don't quite follow your solution, adding your configuration is not really working for me
> > > ` error: attribute 'enable' missing
> > > ```
> > >    at /nix/store/sdnwlvck6a2l6lvl7q9chsqv4m737wjn-source/homeManagerModules/neo.nix:17:20:
> > > 
> > >        16|     };
> > >        17|     config = mkIf (config.nixvim.enable && cfg.enable) {
> > >          |                    ^
> > >        18|       programs = {
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > `
> > 
> > 
> > This is a minimal module without custom options:
> > ```nix
> > {pkgs, ...}: {
> >   programs = {
> >     nixvim = {
> >       enable = true;
> >       extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
> >       extraConfigLuaPost = ''
> >         require("neorg").setup {
> >           load = {
> >             ["core.defaults"] = {},
> >           },
> >         }
> >       '';
> >     };
> >   };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note that this uses the mentioned [overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay). To use it, you have to first be using flakes, and then add it as a flake input in your `flake.nix` and add the overlay to the overlays of your `nixpkgs`. The [link](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) gives an example on how to do that.
> 
> Thank you for your support and help, you helped me learn something new. I was not aware that under a home-manager set up I had to import the overlay directly on my home.nix ( my file structure is something like: flake.nix that imports configuration.nix (os) and in turn configuration.nix imports home.nix (home-manager)).
> 
> In essence by adding the overlay to home-manager solved the issue and I now have Neorg in my Nixvim configuration using the overlay!
> 
> Thank you!

Yeah, you can either import the overlay in `flake.nix` and pass your `pkgs` instance as extraSpecialArgs to home-manager, or use the overlay directly in home-manager. Glad I could help!

**Comment by sij1nk** [comment]
[[>  Error 16:39:43 msg_show.lua_error Lazy build neorg Error executing vim.schedule lua callback: ...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:27: [luarocks] Failed to install from rockspec Warning: Failed searching manifest: Failed extracting manifest file: failed extracting /home/think-crag/.cache/luarocks/https___luarocks.org/manifest-5.1.zip Warning: Failed searching manifest: Failed loading manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/: /home/think-crag/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest-5.1: No such file or directory Warning: Failed searching manifest: Failed loading manifest for https://luafr.org/luarocks/: /home/think-crag/.cache/luarocks/https___luafr.org_luarocks/manifest-5.1: No such file or directory Warning: Failed searching manifest: Failed downloading http://luarocks.logiceditor.com/rocks/manifest-5.1 - failed downloading http://luarocks.logiceditor.com/rocks/manifest-5.1
> 
> Error: Could not satisfy dependency nvim-nio ~> 1.7: No results matching query were found for Lua 5.1. Missing dependencies for neovim-rocks-user-rockspec 0.0-0: nvim-nio ~> 1.7 (not installed) lua-utils.nvim 1.0.2 (not installed) plenary.nvim 0.1.4 (not installed) nui.nvim 0.3.0 (not installed)
> 
> neovim-rocks-user-rockspec 0.0-0 depends on nvim-nio ~> 1.7 (not installed)
> 
> stack traceback: [C]: in function 'assert' ...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:27: in function 'install' ...hare/nvim/lazy/luarocks.nvim/lua/luarocks-nvim/rocks.lua:60: in function 'ensure' /home/think-crag/.local/share/nvim/lazy/neorg/build.lua:14: in function </home/think-crag/.local/share/nvim/lazy/neorg/build.lua:9>

](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2024108469)](https://github.com/nvim-neorg/neorg/issues/1342#issuecomment-2024108469)

It turns out that if anything is "wrong" with `wget`, the Neorg build process (e.g. as invoked through `:Lazy build neorg"`) dies, like in the linked comment above. In my case, after I transferred some dotfiles from another machine, my `WGETRC` environment variable was (mistakenly) pointed to a file which didn't exist, and `wget` failed with the following error:

`wget: WGETRC points to /home/rg/does-not-exist, which couldn't be accessed because of error: No such file or directory.`

Fixing up the `WGETRC` env var to point to a valid wgetrc file cured my `wget`, installing Neorg worked fine afterwards

**Comment by TLSingh1** [comment]
> @arunoruto I also use `nixvim`, did not have any luck either using their plugin option. However, I managed to fix it using the official [neorg-overlay](https://github.com/nvim-neorg/nixpkgs-neorg-overlay) instead and adding the overridden plugin manually:
> 
> ```nix
> {
>   pkgs,
>   config,
>   lib,
>   ...
> }: let
>   cfg = config.nixvim.neorg;
> in
>   with lib; {
>     options = {
>       nixvim = {
>         neorg = {
>           enable = mkEnableOption "Enable neorg for nixvim" // {default = true;};
>         };
>       };
>     };
>     config = mkIf (config.nixvim.enable && cfg.enable) {
>       programs = {
>         nixvim = {
>           extraPlugins = with pkgs.vimPlugins; [neorg neorg-telescope];
>           extraConfigLuaPost =
>             /*
>             lua
>             */
>             ''
>               require("neorg").setup {
>                 load = {
>                   ["core.defaults"] = {}
>                 }
>               }
>             '';
>         };
>       };
>     };
>   }
> ```

This works!! if on nixos, using flakes and home-manager, this solved my issues.

**Comment by sbaumohl** [comment]
After following all steps and troubleshooting steps, and rebuilding neorg multiple times, I keep having this error on checkhealth:

```
[neorg] (01:32:02)
.../.local/share/nvim/lazy/neorg/lua/neorg/core/modules.lua:449
Unable to load module 'core.neorg.dirman'. The module probably does not exist! Stacktrace:  module 'neorg.modules.core.neorg.dirman.module' not found:No LuaRocks module found for neorg.mod
ules.core.neorg.dirman.module
^Ino field package.preload['neorg.modules.core.neorg.dirman.module']
cache_loader: module neorg.modules.core.neorg.dirman.module not found
cache_loader_lib: module neorg.modules.core.neorg.dirman.module not found
^Ino file './neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/usr/local/share/lua/5.1/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/usr/local/share/lua/5.1/neorg/modules/core/neorg/dirman/module/init.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neorg/modules/core/neorg/dirman/module/init.lua'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/share/lua/5.1/neorg/modules/core/neorg/dirman/module/init.lua'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/lua/neorg/modules/core/neorg/dirman/module/init.lua'
^Ino file '/home/simba/.luarocks/share/lua/5.1/neorg/modules/core/neorg/dirman/module.lua'
^Ino file '/home/simba/.luarocks/share/lua/5.1/neorg/modules/core/neorg/dirman/module/init.lua'
^Ino file './neorg/modules/core/neorg/dirman/module.so'
^Ino file '/usr/local/lib/lua/5.1/neorg/modules/core/neorg/dirman/module.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/neorg/modules/core/neorg/dirman/module.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg/modules/core/neorg/dirman/module.so'
^Ino file '/home/simba/.luarocks/lib/lua/5.1/neorg/modules/core/neorg/dirman/module.so'
^Ino file './neorg.so'
^Ino file '/usr/local/lib/lua/5.1/neorg.so'
^Ino file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/neorg.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/home/simba/.local/share/nvim/lazy/luarocks.nvim/.rocks/lib/lua/5.1/neorg.so'
^Ino file '/home/simba/.luarocks/lib/lua/5.1/neorg.so'
Press ENTER or type command to continue                                                                                             
```

**Comment by benlubas** [comment]
@sbaumohl 

> After following all steps and troubleshooting steps, and rebuilding neorg multiple times, I keep having this error on checkhealth:

b/c `core.neorg.dirman` doesn't exist. It's `core.dirman`

**Comment by sbaumohl** [comment]
> @sbaumohl
> 
> > After following all steps and troubleshooting steps, and rebuilding neorg multiple times, I keep having this error on checkhealth:
> 
> b/c `core.neorg.dirman` doesn't exist. It's `core.dirman`

Right. Which is odd because this is my config:

```
        {
                "nvim-neorg/neorg",
                dependencies = { "luarocks.nvim", "nvim-treesitter/nvim-treesitter" },
                lazy = false, -- Disable lazy loading as some `lazy.nvim` distributions set `lazy = true` by default
                version = "*",
                after = "nvim-treesitter",
                config = function()
                        require("neorg").setup({
                                load = {
                                        ["core.defaults"] = {},
                                        ["core.dirman"] = {
                                                config = {
                                                        workspaces = {
                                                                notes = "~/notes",
                                                        },
                                                        index = "index.norg",
                                                },
                                        },
                                },
                        })
                end,
        },
 ```

**Comment by benlubas** [comment]
Well that config works perfectly fine for me, so you must have something else going on. If you push your changes to github, I can poke around. The config on github right now has "core.neorg.dirman"

**Comment by sbaumohl** [comment]
> Well that config works perfectly fine for me, so you must have something else going on. If you push your changes to github, I can poke around. The config on github right now has "core.neorg.dirman"

Ah. The issue was caused by a conflict between two different configs, one of which referenced dirman incorrectly. Neorg is all good now. Thank you!

**Comment by rmacklin** [comment]
In case it's helpful to anyone, [mise](https://github.com/jdx/mise) can be used to install lua 5.1 with luarocks:
```sh
mise plugins add lua
mise use -g lua@5.1
```
after which `luarocks` should be available from `~/.local/share/mise/installs/lua/5.1/luarocks/bin/luarocks`.

**Comment by ilan-schemoul** [comment]
I also had the bug of lua-utils not found.
Neorg **_again_** updated in a breaking manner how to install it (I wish the maintainer kept things simple. KISS is by far the most important principle in programming).
We now need to update Lazy itself, Neorg and update
